<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTipoPagosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tipo_pagos', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('codigoClasificador');
            $table->string('nombre_tipo_pago', 250)->nullable();
            $table->timestamps();
        });
        DB::table('tipo_pagos')->insert([
            [
                'codigoClasificador' => 1,
                'nombre_tipo_pago' => 'EFECTIVO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 2,
                'nombre_tipo_pago' => 'TARJETA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 3,
                'nombre_tipo_pago' => 'CHEQUE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 4,
                'nombre_tipo_pago' => 'VALES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 5,
                'nombre_tipo_pago' => 'OTROS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 6,
                'nombre_tipo_pago' => 'PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 7,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 8,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 9,
                'nombre_tipo_pago' => 'TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 10,
                'nombre_tipo_pago' => 'EFECTIVO-TARJETA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 11,
                'nombre_tipo_pago' => 'EFECTIVO-CHEQUE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 12,
                'nombre_tipo_pago' => 'EFECTIVO-VALES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 13,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 14,
                'nombre_tipo_pago' => 'EFECTIVO-DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 15,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 16,
                'nombre_tipo_pago' => 'TARJETA-CHEQUE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 17,
                'nombre_tipo_pago' => 'TARJETA-VALES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 18,
                'nombre_tipo_pago' => 'TARJETA-TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 19,
                'nombre_tipo_pago' => 'TARJETA-DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 20,
                'nombre_tipo_pago' => 'TARJETA-TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 21,
                'nombre_tipo_pago' => 'VALES-TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 22,
                'nombre_tipo_pago' => 'VALES – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 23,
                'nombre_tipo_pago' => 'VALES-TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 24,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA-DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 25,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA-TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 26,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 27,
                'nombre_tipo_pago' => 'GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 28,
                'nombre_tipo_pago' => 'GIFT-CARD-1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 29,
                'nombre_tipo_pago' => 'GIFT-CARD-2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 30,
                'nombre_tipo_pago' => 'GIFT-CARD OTROS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 31,
                'nombre_tipo_pago' => 'CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 32,
                'nombre_tipo_pago' => 'BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 33,
                'nombre_tipo_pago' => 'PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 34,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 35,
                'nombre_tipo_pago' => 'EFECTIVO – GIFT CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 36,
                'nombre_tipo_pago' => 'EFECTIVO – CANAL PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 37,
                'nombre_tipo_pago' => 'EFECTIVO – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 38,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 39,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 40,
                'nombre_tipo_pago' => 'TARJETA – GIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 41,
                'nombre_tipo_pago' => 'TARJETA – CANAL PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 42,
                'nombre_tipo_pago' => 'TARJETA – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 43,
                'nombre_tipo_pago' => 'TARJETA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 44,
                'nombre_tipo_pago' => 'CHEQUE – VALES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 45,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 46,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 47,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 48,
                'nombre_tipo_pago' => 'CHEQUE – SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 49,
                'nombre_tipo_pago' => 'CHEQUE – GIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 50,
                'nombre_tipo_pago' => 'CHEQUE – CANAL PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 51,
                'nombre_tipo_pago' => 'CHEQUE – BILLETERA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 52,
                'nombre_tipo_pago' => 'CHEQUE – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 53,
                'nombre_tipo_pago' => 'VALES – GIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 54,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 55,
                'nombre_tipo_pago' => 'VALES – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 56,
                'nombre_tipo_pago' => 'VALES – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 57,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 58,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 59,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 60,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – GIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 61,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – CANAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 62,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – BILLETERA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 63,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 64,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 65,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 66,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 67,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 68,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 69,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 70,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 71,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 72,
                'nombre_tipo_pago' => 'SWIFT – GIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 73,
                'nombre_tipo_pago' => 'SWIFT – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 74,
                'nombre_tipo_pago' => 'SWIFT – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 75,
                'nombre_tipo_pago' => 'SWIFT – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 76,
                'nombre_tipo_pago' => 'GIFT-CARD – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 77,
                'nombre_tipo_pago' => 'GIFT – BILLETERA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 78,
                'nombre_tipo_pago' => 'GIFT – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 79,
                'nombre_tipo_pago' => 'CANAL DE PAGO – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 80,
                'nombre_tipo_pago' => 'CANAL DE PAGO – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 81,
                'nombre_tipo_pago' => 'BILLETERA MOVIL – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 82,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 83,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 84,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 85,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 86,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 87,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 88,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 89,
                'nombre_tipo_pago' => 'EFECTIVO - TARJETA - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 90,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 91,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 92,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 93,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 94,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 95,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 96,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 97,
                'nombre_tipo_pago' => 'EFECTIVO – CHEQUE - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 98,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 99,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 100,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 101,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 102,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 103,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 104,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 105,
                'nombre_tipo_pago' => 'EFECTIVO – VALES - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 106,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 107,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 108,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 109,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 110,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 111,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 112,
                'nombre_tipo_pago' => 'EFECTIVO – PAGO POSTERIOR - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 113,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 114,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 115,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 116,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 117,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 118,
                'nombre_tipo_pago' => 'EFECTIVO – TRANSFERENCIA BANCARIA  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 119,
                'nombre_tipo_pago' => 'EFECTIVO – DEPOSITO EN CUENTA  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 120,
                'nombre_tipo_pago' => 'EFECTIVO – DEPOSITO EN CUENTA  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 121,
                'nombre_tipo_pago' => 'EFECTIVO – DEPOSITO EN CUENTA  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 122,
                'nombre_tipo_pago' => 'EFECTIVO – DEPOSITO EN CUENTA  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 123,
                'nombre_tipo_pago' => 'EFECTIVO – DEPOSITO EN CUENTA  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 124,
                'nombre_tipo_pago' => 'EFECTIVO – SWIFT - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 125,
                'nombre_tipo_pago' => 'EFECTIVO – SWIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 126,
                'nombre_tipo_pago' => 'EFECTIVO – SWIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 127,
                'nombre_tipo_pago' => 'EFECTIVO – SWIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 128,
                'nombre_tipo_pago' => 'EFECTIVO – GIFT CARD - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 129,
                'nombre_tipo_pago' => 'EFECTIVO – GIFT CARD - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 130,
                'nombre_tipo_pago' => 'EFECTIVO – GIFT CARD - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 131,
                'nombre_tipo_pago' => 'EFECTIVO – CANAL PAGO - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 132,
                'nombre_tipo_pago' => 'EFECTIVO – CANAL PAGO - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 133,
                'nombre_tipo_pago' => 'EFECTIVO – BILLETERA MOVIL - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 134,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 135,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 136,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 137,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 138,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 139,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 140,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 141,
                'nombre_tipo_pago' => 'TARJETA – CHEQUE - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 142,
                'nombre_tipo_pago' => 'TARJETA – VALES - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 143,
                'nombre_tipo_pago' => 'TARJETA – VALES - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 144,
                'nombre_tipo_pago' => 'TARJETA – VALES - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 145,
                'nombre_tipo_pago' => 'TARJETA – VALES - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 146,
                'nombre_tipo_pago' => 'TARJETA – VALES - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 147,
                'nombre_tipo_pago' => 'TARJETA – VALES - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 148,
                'nombre_tipo_pago' => 'TARJETA – VALES - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 149,
                'nombre_tipo_pago' => 'TARJETA – VALES - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 150,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 151,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 152,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 153,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 154,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 155,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 156,
                'nombre_tipo_pago' => 'TARJETA – PAGO POSTERIOR - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 157,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA BANCARIA – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 158,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 159,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA BANCARIA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 160,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA BANCARIA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 161,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA  BANCARIA – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 162,
                'nombre_tipo_pago' => 'TARJETA – TRANSFERENCIA BANCARIA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 163,
                'nombre_tipo_pago' => 'TARJETA – DEPOSITO EN CUENTA – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 164,
                'nombre_tipo_pago' => 'TARJETA – DEPOSITO EN CUENTA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 165,
                'nombre_tipo_pago' => 'TARJETA – DEPOSITO EN CUENTA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 166,
                'nombre_tipo_pago' => 'TARJETA – DEPOSITO EN CUENTA  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 167,
                'nombre_tipo_pago' => 'TARJETA – DEPOSITO EN CUENTA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 168,
                'nombre_tipo_pago' => 'TARJETA – SWIFT - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 169,
                'nombre_tipo_pago' => 'TARJETA – SWIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 170,
                'nombre_tipo_pago' => 'TARJETA – SWIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 171,
                'nombre_tipo_pago' => 'TARJETA – SWIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 172,
                'nombre_tipo_pago' => 'TARJETA – GIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 173,
                'nombre_tipo_pago' => 'TARJETA – GIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 174,
                'nombre_tipo_pago' => 'TARJETA – GIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 175,
                'nombre_tipo_pago' => 'TARJETA – CANAL PAGO - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 176,
                'nombre_tipo_pago' => 'TARJETA – CANAL PAGO - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 177,
                'nombre_tipo_pago' => 'TARJETA – BILLETERA MOVIL - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 178,
                'nombre_tipo_pago' => 'CHEQUE – VALES - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 179,
                'nombre_tipo_pago' => 'CHEQUE – VALES - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 180,
                'nombre_tipo_pago' => 'CHEQUE – VALES - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 181,
                'nombre_tipo_pago' => 'CHEQUE – VALES - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 182,
                'nombre_tipo_pago' => 'CHEQUE – VALES - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 183,
                'nombre_tipo_pago' => 'CHEQUE – VALES - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 184,
                'nombre_tipo_pago' => 'CHEQUE – VALES - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 185,
                'nombre_tipo_pago' => 'CHEQUE – VALES - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 186,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 187,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 188,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 189,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 190,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 191,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 192,
                'nombre_tipo_pago' => 'CHEQUE – PAGO POSTERIOR - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 193,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 194,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 195,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 196,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 197,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 198,
                'nombre_tipo_pago' => 'CHEQUE – TRANSFERENCIA BANCARIA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 199,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 200,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO EN CUENTA - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 201,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO EN CUENTA - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 202,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO EN CUENTA - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 203,
                'nombre_tipo_pago' => 'CHEQUE – DEPOSITO EN CUENTA - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 204,
                'nombre_tipo_pago' => 'CHEQUE – SWIFT - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 205,
                'nombre_tipo_pago' => 'CHEQUE – SWIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 206,
                'nombre_tipo_pago' => 'CHEQUE – SWIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 207,
                'nombre_tipo_pago' => 'CHEQUE – SWIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 208,
                'nombre_tipo_pago' => 'CHEQUE – GIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 209,
                'nombre_tipo_pago' => 'CHEQUE – GIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 210,
                'nombre_tipo_pago' => 'CHEQUE – GIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 211,
                'nombre_tipo_pago' => 'CHEQUE – CANAL PAGO - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 212,
                'nombre_tipo_pago' => 'CHEQUE – CANAL PAGO - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 213,
                'nombre_tipo_pago' => 'CHEQUE – BILLETERA MOVIL  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 214,
                'nombre_tipo_pago' => 'VALES – SWIFT - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 215,
                'nombre_tipo_pago' => 'VALES – SWIFT - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 216,
                'nombre_tipo_pago' => 'VALES – SWIFT - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 217,
                'nombre_tipo_pago' => 'VALES – SWIFT - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 218,
                'nombre_tipo_pago' => 'VALES – SWIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 219,
                'nombre_tipo_pago' => 'VALES – SWIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 220,
                'nombre_tipo_pago' => 'VALES – SWIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 221,
                'nombre_tipo_pago' => 'VALES – GIFT - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 222,
                'nombre_tipo_pago' => 'VALES – GIFT - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 223,
                'nombre_tipo_pago' => 'VALES – GIFT-CARD – TARJETA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 224,
                'nombre_tipo_pago' => 'VALES – GIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 225,
                'nombre_tipo_pago' => 'VALES – GIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 226,
                'nombre_tipo_pago' => 'VALES – GIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 227,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 228,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 229,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 230,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 231,
                'nombre_tipo_pago' => 'VALES – CANAL DE PAGO  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 232,
                'nombre_tipo_pago' => 'VALES – BILLETERA MOVIL – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 233,
                'nombre_tipo_pago' => 'VALES – BILLETERA MOVIL – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 234,
                'nombre_tipo_pago' => 'VALES – BILLETERA MOVIL – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 235,
                'nombre_tipo_pago' => 'VALES – BILLETERA MOVIL – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 236,
                'nombre_tipo_pago' => 'VALES – PAGO ONLINE - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 237,
                'nombre_tipo_pago' => 'VALES – PAGO ONLINE - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 238,
                'nombre_tipo_pago' => 'VALES – PAGO ONLINE - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 239,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 240,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 241,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 242,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 243,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 244,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – TRANSFERENCIA BANCARIA  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 245,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 246,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 247,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 248,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 249,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – DEPOSITO EN CUENTA  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 250,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – SWIFT - GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 251,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – SWIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 252,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – SWIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 253,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – SWIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 254,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – GIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 255,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – GIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 256,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – GIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 257,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – CANAL DE PAGO - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 258,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – CANAL DE PAGO - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 259,
                'nombre_tipo_pago' => 'PAGO POSTERIOR – BILLETERA MOVIL - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 260,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – DEPOSITO EN CUENTA  – TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 261,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – DEPOSITO  EN CUENTA – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 262,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – DEPOSITO  EN CUENTA – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 263,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – DEPOSITO EN CUENTA   – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 264,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA– DEPOSITO  EN CUENTA – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 265,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – SWIFT  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 266,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – SWIFT  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 267,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – SWIFT  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 268,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – SWIFT  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 269,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – GIFT-CARD  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 270,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – GIFT-CARD  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 271,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – GIFT-CARD  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 272,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – CANAL DE PAGO – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 273,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – CANAL DE PAGO – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 274,
                'nombre_tipo_pago' => 'TRANSFERENCIA BANCARIA – BILLETERA MOVIL – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 275,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – SWIFT  – GIFT-CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 276,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – SWIFT  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 277,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – SWIFT  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 278,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – SWIFT  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 279,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – GIFT-CARD  – CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 280,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – GIFT-CARD  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 281,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA  – GIFT-CARD  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 282,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA –  CANAL DE PAGO  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 283,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – CANAL DE PAGO   – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 284,
                'nombre_tipo_pago' => 'DEPOSITO EN CUENTA – BILLETERA MOVIL  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 285,
                'nombre_tipo_pago' => 'SWIFT – GIFT - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 286,
                'nombre_tipo_pago' => 'SWIFT – GIFT - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 287,
                'nombre_tipo_pago' => 'SWIFT – GIFT - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 288,
                'nombre_tipo_pago' => 'SWIFT – CANAL DE PAGO  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 289,
                'nombre_tipo_pago' => 'SWIFT – CANAL  DE PAGO – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 290,
                'nombre_tipo_pago' => 'SWIFT – BILLETERA MOVIL  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 291,
                'nombre_tipo_pago' => 'GIFT-CARD – CANAL DE PAGO  – BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 292,
                'nombre_tipo_pago' => 'GIFT-CARD – CANAL DE PAGO  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 293,
                'nombre_tipo_pago' => 'GIFT-CARD – BILLETERA MOVIL - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 294,
                'nombre_tipo_pago' => 'CANAL DE PAGO – BILLETERA MOVIL  – PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 295,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 296,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO – EFECTIVO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 297,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO -TARJETA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 298,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO – CHEQUE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 299,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - VALE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 300,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - PAGO POSTERIOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 301,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - TRANSFERENCIA BANCARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 302,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - DEPOSITO EN CUENTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 303,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - TRANSFERENCIA SWIFT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 304,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - GIFT CARD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 305,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - CANAL DE PAGO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 306,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - BILLETERA MOVIL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 307,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO - PAGO ONLINE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigoClasificador' => 308,
                'nombre_tipo_pago' => 'DEBITO AUTOMATICO – OTRO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tipo_pagos');
    }
}
